#!/bin/bash

# Copy the latest screenshot into the current directory
# Usage:  cpsc <file_name>

source_dir=~/Pictures/Screenshots/
latest_image=$(ls -t $source_dir | head -1)
extension="${latest_image##*.}"
filename=$1

if [[ -z $filename ]]; then
  echo "Please provide a filename as the first argument."
  exit 1
fi
new_file="$filename.$extension"

cp "$source_dir/$latest_image" "./$new_file"
echo "Copied $latest_image to $new_file."
