#!/bin/bash

# list all local merged branches, to-be-pruned remotes by git_rm_merged

echo ""
echo "Local merged branches"
printf "___________\n"
git branch --merged | grep -Ev "(^\*|origin|master|main|dev)"
printf "\n\n"

echo "Local to-be-pruned origin remotes"
printf "___________\n"
git remote prune origin --dry-run | grep -v "Pruning origin" | grep -v "URL: " | sed 's/ \* \[would prune\] //'
printf "\n\n"
